[project]
name = "sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.6.0",
    "ipykernel>=6.29.5",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]
